# Generated by Django 3.2.9 on 2022-01-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20220130_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internships',
            old_name='end_date',
            new_name='end_period',
        ),
        migrations.RenameField(
            model_name='internships',
            old_name='start_date',
            new_name='start_period',
        ),
    ]
