# Generated by Django 3.2.9 on 2022-02-14 04:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recruitment.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0003_auto_20220130_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tet', models.CharField(max_length=254)),
                ('title_por', models.CharField(max_length=254, null=True)),
                ('title_eng', models.CharField(max_length=254, null=True)),
                ('description_tet', models.TextField(blank=True, null=True)),
                ('description_por', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('start_period', models.DateField(blank=True, null=True)),
                ('end_period', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=recruitment.utils.path_and_rename_volunteer_image)),
                ('file', models.FileField(upload_to=recruitment.utils.path_and_rename_vacancy_pdf, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
