# Generated by Django 3.2.9 on 2022-02-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_send_notif',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
