# Generated by Django 3.2.9 on 2022-02-01 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_auto_20220128_1524'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tet', models.CharField(max_length=254)),
                ('name_por', models.CharField(max_length=254, null=True)),
                ('name_eng', models.CharField(max_length=254, null=True)),
                ('overview_tet', models.TextField(blank=True, null=True)),
                ('overview_por', models.TextField(blank=True, null=True)),
                ('overview_eng', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=gallery.utils.path_and_rename_album_image)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_tet', models.TextField(blank=True, null=True)),
                ('overview_por', models.TextField(blank=True, null=True)),
                ('overview_eng', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to=gallery.utils.path_and_rename_gallery_image, verbose_name='Upload Imajen')),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.album', verbose_name='Album')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
