# Generated by Django 3.2.9 on 2022-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20220201_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='overview_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Deskrisaun (Ingles) '),
        ),
        migrations.AlterField(
            model_name='album',
            name='overview_por',
            field=models.TextField(blank=True, null=True, verbose_name='Deskrisaun (Portugues) '),
        ),
        migrations.AlterField(
            model_name='album',
            name='overview_tet',
            field=models.TextField(blank=True, null=True, verbose_name='Deskrisaun (Tetum) '),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='overview_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Deskrisaun (Ingles)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='overview_por',
            field=models.TextField(blank=True, null=True, verbose_name='Deskrisaun (Portugues)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='overview_tet',
            field=models.TextField(blank=True, null=True, verbose_name='Deskrisaun (Tetum)'),
        ),
    ]
