# Generated by Django 3.2.9 on 2022-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20220201_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalerryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hashed', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
