# Generated by Django 3.2.9 on 2022-02-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_video_videocategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
