# Generated by Django 3.2.9 on 2022-02-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20220216_2107'),
        ('gallery', '0009_alter_album_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.videocategory'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
