# Generated by Django 3.2.9 on 2022-02-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_send_notif',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
