# Generated by Django 3.2.9 on 2022-01-27 00:00

import departments.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tet', models.CharField(max_length=254)),
                ('name_por', models.CharField(max_length=254, null=True)),
                ('name_eng', models.CharField(max_length=254, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=departments.utils.path_and_rename_department)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tet', models.CharField(max_length=254)),
                ('name_por', models.CharField(max_length=254, null=True)),
                ('name_eng', models.CharField(max_length=254, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=departments.utils.path_and_rename_department)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
