# Generated by Django 3.2.9 on 2022-01-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20220127_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='overview',
            new_name='overview_eng',
        ),
        migrations.AddField(
            model_name='department',
            name='overview_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='overview_tet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
