# Generated by Django 3.2.9 on 2022-01-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20220128_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='overview',
            new_name='overview_eng',
        ),
        migrations.AddField(
            model_name='division',
            name='overview_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='overview_tet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
