# Generated by Django 3.2.9 on 2022-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_division_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='title_seo_eng',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='title_seo_por',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='title_seo_tet',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
