# Generated by Django 3.2.9 on 2022-02-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_auto_20220216_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='title_seo_eng',
            new_name='title_seo',
        ),
        migrations.RemoveField(
            model_name='department',
            name='title_seo_por',
        ),
        migrations.RemoveField(
            model_name='department',
            name='title_seo_tet',
        ),
    ]
