# Generated by Django 3.2.9 on 2022-02-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='title',
            new_name='title_eng',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='language',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title_seo',
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_tet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_por',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_tet',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
