from .admin import *
from .main import *
from .employee import *
from .about import *
from .vacancy import *
from .appointment import *
from .news import *
from .event import *
from .resource import *
from .report import *
from .documentary import *
from .tender import *
from .project import *
from .announcement import *
from .album import *
from .fms import *
from .usm import *