# Generated by Django 3.2.9 on 2022-01-19 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import news.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hashed', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='news',
            name='email',
        ),
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
        migrations.RemoveField(
            model_name='news',
            name='subject',
        ),
        migrations.AddField(
            model_name='news',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Aprova husi'),
        ),
        migrations.AddField(
            model_name='news',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_entered_by', to=settings.AUTH_USER_MODEL, verbose_name='Prenche husi'),
        ),
        migrations.AddField(
            model_name='news',
            name='entered_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_seo',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_tet', models.CharField(max_length=200, null=True)),
                ('description_por', models.CharField(max_length=200, null=True)),
                ('description_eng', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to=news.utils.path_and_rename_news, verbose_name='Upload Imajen')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsimage', to='news.news', verbose_name='Noticia')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='kategoria'),
        ),
    ]
