# Generated by Django 3.2.9 on 2022-01-20 00:08

from django.db import migrations
import imagekit.models.fields
import news.utils


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_entered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=news.utils.path_and_rename_news, verbose_name='Upload Imajen'),
        ),
    ]
