# Generated by Django 3.2.9 on 2022-01-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='entered_by',
        ),
    ]
