# Generated by Django 3.2.9 on 2022-01-20 02:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='news-image/', verbose_name='Upload Imajen'),
        ),
    ]
