# Generated by Django 3.2.9 on 2022-01-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
