# Generated by Django 3.2.9 on 2022-01-20 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20220120_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
