# Generated by Django 3.2.9 on 2022-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_is_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
