# Generated by Django 3.2.9 on 2022-02-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_news_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_cat', to='news.newscategory', verbose_name='News Category'),
        ),
    ]
