# Generated by Django 3.2.9 on 2022-02-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='name',
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_eng',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_por',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_tet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
