# Generated by Django 3.2.9 on 2022-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_subscribechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribechoice',
            name='hashed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
