# Generated by Django 3.2.9 on 2022-02-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_subscribechoice_hashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsuser',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='newsuser',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribechoice',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
