# Generated by Django 3.2.9 on 2022-02-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_newscomment_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='is_active',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='newscomment',
            name='is_reject',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
