# Generated by Django 3.2.9 on 2022-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_newscomment_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
