# Generated by Django 3.2.9 on 2022-02-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_ipmodel'),
        ('news', '0026_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='custom.IpModel'),
        ),
    ]
