# Generated by Django 3.2.9 on 2022-01-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidelines',
            name='end_period',
        ),
        migrations.RemoveField(
            model_name='guidelines',
            name='start_period',
        ),
    ]
