# Generated by Django 3.2.9 on 2022-02-14 03:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import procurament.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurament', '0002_auto_20220130_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tet', models.CharField(max_length=254)),
                ('title_por', models.CharField(max_length=254, null=True)),
                ('title_eng', models.CharField(max_length=254, null=True)),
                ('description_tet', models.TextField(blank=True, null=True)),
                ('description_por', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=procurament.utils.path_and_rename_policy_pdf, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
