# Generated by Django 3.2.9 on 2022-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurament', '0003_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='is_send_notif',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
