# Generated by Django 3.2.9 on 2022-01-29 05:46

from django.db import migrations, models
import report.utils


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20220129_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=report.utils.path_and_rename_report_image),
        ),
    ]
