# Generated by Django 3.2.9 on 2022-02-04 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faq.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tet', models.CharField(max_length=254)),
                ('name_por', models.CharField(max_length=254, null=True)),
                ('name_eng', models.CharField(max_length=254, null=True)),
                ('overview_tet', models.TextField(blank=True, null=True)),
                ('overview_por', models.TextField(blank=True, null=True)),
                ('overview_eng', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=faq.utils.path_and_rename_faq_image)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
