# Generated by Django 3.2.9 on 2022-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_homepage',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
