# Generated by Django 3.2.9 on 2022-02-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
