# Generated by Django 3.2.9 on 2022-02-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reject_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reply_comment',
            field=models.TextField(null=True),
        ),
    ]
