# Generated by Django 3.2.9 on 2022-02-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20220204_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reject_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reply_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
