# Generated by Django 3.2.9 on 2022-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='done_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_donde',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
