# Generated by Django 3.2.9 on 2022-02-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20220204_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_donde',
            new_name='is_done',
        ),
    ]
