# Generated by Django 3.2.9 on 2022-02-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_rename_is_donde_appointment_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
