# Generated by Django 3.2.9 on 2022-02-04 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointmentto'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointmentto'),
        ),
    ]
