# Generated by Django 3.2.9 on 2022-02-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_appointment_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentto',
            name='name_to',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='approved_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reject_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reply_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
