# Generated by Django 3.2.9 on 2022-02-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20220204_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_finish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
