# Generated by Django 3.2.9 on 2022-02-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_appointment_is_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointmentto'),
        ),
    ]
