# Generated by Django 3.2.9 on 2022-02-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_appointment_appointment_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_finish',
            new_name='is_cancelled',
        ),
    ]
