# Generated by Django 3.2.9 on 2022-02-12 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0014_contactmunicipality_municipality_position_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmunicipality',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
