# Generated by Django 3.2.9 on 2022-02-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_auto_20220212_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmunicipality',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
