# Generated by Django 3.2.9 on 2022-02-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_remove_suggestion_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='last_name',
        ),
    ]
