# Generated by Django 3.2.9 on 2022-02-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_auto_20220212_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
