# Generated by Django 3.2.9 on 2022-01-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbudget',
            old_name='oge_estimation',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='owner_estimation',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='yearly_allocation',
        ),
    ]
