# Generated by Django 3.2.9 on 2022-01-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220130_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
