# Generated by Django 3.2.9 on 2022-01-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20220130_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
