# Generated by Django 3.2.9 on 2022-01-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20220131_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudget',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
