# Generated by Django 3.2.9 on 2022-01-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_hashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProcurament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='typeofprocurament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.typeofprocurament'),
        ),
    ]
