# Generated by Django 3.2.9 on 2022-01-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20220131_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='author',
        ),
    ]
