# Generated by Django 3.2.9 on 2022-01-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_user_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudget',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
