# Generated by Django 3.2.9 on 2022-02-01 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_projectbudget_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='typeofprocurament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.typeofprocurament', verbose_name='Type of Procurament'),
        ),
    ]
