# Generated by Django 3.2.9 on 2022-02-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_typeofprocurament'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
