
def lang_master(lang):
    lang_data = []
    if lang == "tt":
        lang_data = {
            "HOME_LAST_NEWS": "NOTICIA IKUS",
            "BTN_READ_MORE": "Kontinua Le'e",
            "HOME_RECENT": "Foin Publika",
            "HOME_FAQ_TITLE": "Sempre Husu",
            "HOME_VISITOR": "Visitante",
            "HOME_VISITOR_TODAY": "Ohin",
            "HOME_VISITOR_ALL": "Total",
            "HOME_MARQUEE": "Bem Vindo Mai Eletricidade de Timor Leste, Empresa Publika",
            "BREAKCUMB": "Varanda",
            "CATEGORY": "Kategoria",
            "MORE_IMAGES": "Imajen Seluk",
            "SHARE_LBL": "Fahe ba Sosial Media",
            "NO_IMAGE_LBL": "Imajen Laiha",
            "ABOUT_LBL1": "Se mak Ami",
            "ABOUT_LBL2": "Saida mak ami Halo",
            "ABOUT_LBL3": "Membro",
            "BACKGROUND_LBL": "Esperiénsia",
            "MISSION_LBL": "Misaun",
            "VISION_LBL": "Visaun",
            "VALUES_LBL": "Valor",
            "SERVICE_LBL": "WE PROVIDE SERVICES LIKE AMI FORNESE SERVISU HANESAN :",
            "BOARD_MEMBER_LBL": "Membro",
            "BOARD_MEMBER_DEPARTMENT_LBL": "Departamentu",
            "EVENT_LBL": "Lista Eventu",
            "EVENT_TITLE_LBL": "Eventu",
            "EVENT_START_DATE_LBL": "Data Hahu",
            "EVENT_END_DATE_LBL": "Data Remata",
            "EVENT_BREAKCUMB_LBL": "Detalla Eventu",
            "EVENT_INFROMATION_LBL": "Informasaun Kona-ba Eventu",
            "RESOURCE_TITLE_LBL": "Detalla Produtu",
            "DEPARTMENT_TITLE_LBL": "Detalla Departamentu",
            "LIST_DIVISION_TITLE_LBL": "Lista Divisaun",
            "DIVISION_TITLE_LBL": "Detalla Divisaun",
            "REPORT_LIST_LBL": "Lista Relatoriu",
            "REPORT_TITLE_LBL": "RELATORIU",
            "REPORT_TITLE__DETAIL_LBL": "Detala Relatoriu",
            "REPORT_DESCRIPTION_LBL": "Informasaun Relatoriu",
            "VACANCY_LIST_LBL": "Lista Vaga",
            "VACANCY_TITLE_LBL": "VAGA",
            "TABEL_LBL1": "Pozisaun",
            "TABEL_LBL6": "Titulu",
            "TABEL_LBL2": "Deskrisaun",
            "TABEL_LBL3": "Periodu Hahu",
            "TABEL_LBL4": "Periodu Remata",
            "TABEL_LBL5": "Asaun",
            "TABEL_LBL9": "Naran Projetu",
            "TABEL_LBL7": "Kategoria",
            "TABEL_LBL8": "Kompania",
            "ACTIVE_LBL": "Ativu",
            "EXPIRED_LBL": "Expiradu",
            "INTERNSHIP_LIST_LBL": "Lista Estajiu",
            "INTERNSHIP_TITLE_LBL": "ESTAJIU",
            "VOLUNTEER_LIST_LBL": "Lista Voluntariu",
            "VOLUNTEER_TITLE_LBL": "VOLUNTARIU",
            "TENDER_LIST_LBL": "Lista Tenderizasaun ",
            "TENDER_TITLE_LBL": "TENDERIZASAUN",
            "PROCURAMENT_LIST_LBL": "Mata Dalan",
            "PROCURAMENT_TITLE_LBL": "MATA DALAN",
            "POLICY_LIST_LBL": "Lista Politika no Regras",
            "POLICY_TITLE_LBL": "POLÍTIKA NO REGRAS",
            "PROJECT_LIST_LBL": "Lista Projetu Progressu",
            "PROJECT_TITLE_LBL": "PROJETU PROGRESSU",
            "PROJECT_DETAIL_LBL": "Detalla Projetu",
            "PROJECT_DETAIL1_LBL": "Informasaun Projetu",
            "PROJECT_DETAIL2_LBL": "Informasaun Kontratu",
            "PROJECT_DETAIL3_LBL": "Informasaun Lokalizasaun",
            "PROJECT_DETAIL4_LBL": "Naran Projetu",
            "PROJECT_DETAIL5_LBL": "Kategoria",
            "PROJECT_DETAIL6_LBL": "Fundu",
            "PROJECT_DETAIL7_LBL": "Tinan",
            "PROJECT_DETAIL8_LBL": "Kompania",
            "PROJECT_DETAIL9_LBL": "Numeru Kontratu",
            "PROJECT_DETAIL10_LBL": "Periode Hahu",
            "PROJECT_DETAIL11_LBL": "Periode Remata",
            "PROJECT_DETAIL12_LBL": "Orsamentu",
            "PROJECT_DETAIL13_LBL": "Munisipiu",
            "PROJECT_DETAIL14_LBL": "Postu Administrativu",
            "PROJECT_DETAIL15_LBL": "Suku",
            "PROJECT_DETAIL16_LBL": "Tipu Prokuramen",
            "PROJECT_NEW_LIST_LBL": "Lista Projetu Foun",
            "PROJECT_NEW_TITLE_LBL": "PROJETU FOUN",
            "ANNOUNCEMENT_LIST_LBL": "Lista Anunsiu",
            "ANNOUNCEMENT_TITLE_LBL": "ANUNSIU",
            "ANNOUNCEMENT_DETAIL_LBL": "Informasaun Anunsiu",
            "ANNOUNCEMENT_DETAIL_BREAKCUMB_LBL": "Detalla Anunsiu",
            "GET_IN_TOUCH_BREAKCUMB_LBL": "Kontaktu",
            "APPOINTMENT_LBL": "PEDIDU ENKONTRU",
            "SUGGESTION_LBL": "SUJESTAUN",
            "CONTACT_MUNICIPALITY_LBL": "PESSOAL EDTL,EP IHA MUNICÍPIO",
            "APPOINTMENT_LBL1": "Prienche Informasun",
            "APPOINTMENT_LBL2": "Naran Kompletu",
            "APPOINTMENT_LBL2_1": "Prienche Naran Kompletu",
            "APPOINTMENT_LBL3": "Email",
            "APPOINTMENT_LBL3_1": "Prienche Email",
            "APPOINTMENT_LBL4": "Numero Telefone",
            "APPOINTMENT_LBL4_1": "Prienche Numeru Telefone",
            "APPOINTMENT_LBL5": "Data Encontru",
            "APPOINTMENT_LBL6": "Oras Encontro",
            "APPOINTMENT_LBL7": "Encontru Ho",
            "APPOINTMENT_LBL8": "Sujeitu",
            "APPOINTMENT_LBL8_1": "Prinche Sujeitu",
            "APPOINTMENT_LBL9": "Submete",
            "APPOINTMENT_LBL10": "Fo Sujestaun",
            "APPOINTMENT_LBL11": "Komentariu",
            "APPOINTMENT_LBL12_1": "Prienche Komentariu",
            "POSITION_LBL": "Pozisaun",
            "LIST_ALBUM_LBL": "Lista Album",
            "DETAIL_ALBUM_LBL": "Detalla Album",
            "DETAIL_ALBUM_INFO_LBL": "Informasaun Album",
            "DETAIL_ALBUM_LBL1": "Kategoria",
            "DETAIL_ALBUM_LBL2": "Deskrisaun",
            "LIST_VIDEO_LBL": "Lista Video",
            "VIDEO_LBL": "Lista Documentariu",
            "FOOTER_LBL1": "Numeru Telefone",
            "FOOTER_LBL2": "Suporta Link",
            "FOOTER_LBL3": "Sistema Manejamentu Finansas (Ba Kliente)",
            "FOOTER_LBL4": "Manejamentu Usuariu",
            "FOOTER_LBL5": "Sempre Husu",
            "FOOTER_LBL6": "Sistema Seluk",
            "FOOTER_LBL7": "Join Our Newsletter",
            "FOOTER_LBL8": "Atu hetan informasaun husi email; Prienche Ita Boot nia Email iha koluna Kraik",
            "FAQ_LBL": "Sempre Husu",
            "FAQ_DETAIL_LBL": "Detalla",
            
        }
    elif lang == "pt":
        lang_data = {
            "HOME_LAST_NEWS": "ÚLTIMAS NOTÍCIAS",
            "BTN_READ_MORE": "Mais Informação",
            "HOME_RECENT": "Últimas Publicações",
            "HOME_FAQ_TITLE": "Perguntas Frequentes",
            "HOME_VISITOR": "Visitante",
            "HOME_VISITOR_TODAY": "Agora",
            "HOME_VISITOR_ALL": "Total",
            "HOME_MARQUEE": "Bem Vindo Ao Eletricidade de Timor Leste, Empresa Pública",
            "BREAKCUMB": "Inicio",
            "CATEGORY": "Categorias",
            "MORE_IMAGES": "Mais Imagem",
            "SHARE_LBL": "Partilha na Mídia Social",
            "NO_IMAGE_LBL": "Sem imagens",
            "ABOUT_LBL1": "Sobre Nós",
            "ABOUT_LBL2": "Nossos Serviços",
            "ABOUT_LBL3": "Perfil do Conselho",
            "BACKGROUND_LBL": "Esperiéncia",
            "MISSION_LBL": "Missão",
            "VISION_LBL": "Visão",
            "VALUES_LBL": "Valores",
            "SERVICE_LBL": "PRESTAMOS SERVIÇOS COMO :",
            "BOARD_MEMBER_LBL": "Membro",
            "BOARD_MEMBER_DEPARTMENT_LBL": "Departamento",
            "EVENT_LBL": "Lista de evento",
            "EVENT_TITLE_LBL": "Evento",
            "EVENT_START_DATE_LBL": "Data de início",
            "EVENT_END_DATE_LBL": "Data Final",
            "EVENT_BREAKCUMB_LBL": "Detalhe do evento",
            "EVENT_INFROMATION_LBL": "Informações sobre o Evento",
            "RESOURCE_TITLE_LBL": "Detalhe do Produto",
            "DEPARTMENT_TITLE_LBL": "Detalhe do Departamento",
            "LIST_DIVISION_TITLE_LBL": "Lista Divisão",
            "DIVISION_TITLE_LBL": "Detalhe Divisão",
            "REPORT_LIST_LBL": "Lista Relatorio",
            "REPORT_TITLE_LBL": "RELATORIO",
            "REPORT_TITLE__DETAIL_LBL": "Detalhe Relatorio",
            "REPORT_DESCRIPTION_LBL": "Informações do Relatório",
            "VACANCY_LIST_LBL": "Lista Vagas",
            "VACANCY_TITLE_LBL": "VAGA",
            "TABEL_LBL1": "Posição",
            "TABEL_LBL2": "Descrição",
            "TABEL_LBL3": "Período Inicial",
            "TABEL_LBL4": "Período Final",
            "TABEL_LBL5": "Açao",
            "TABEL_LBL9": "Nome do Projeto",
            "TABEL_LBL7": "Categoria",
            "TABEL_LBL8": "Companhia",
            "ACTIVE_LBL": "Ativo",
            "EXPIRED_LBL": "Expirado",
            "INTERNSHIP_LIST_LBL": "Lista Estágio",
            "INTERNSHIP_TITLE_LBL": "ESTÁGIOS",
            "TABEL_LBL6": "Título",
            "VOLUNTEER_LIST_LBL": "Lista Voluntário",
            "VOLUNTEER_TITLE_LBL": "VOLUNTÁRIO",
            "TENDER_LIST_LBL": "Lista Tenderização ",
            "TENDER_TITLE_LBL": "TENDERIZAÇÃO",
            "PROCURAMENT_LIST_LBL": "Instrução",
            "PROCURAMENT_TITLE_LBL": "INSTRUÇÃO",
            "POLICY_LIST_LBL": "Lista de Políticas e Regras",
            "POLICY_TITLE_LBL": "POLÍTICA E REGRAS",
            "PROJECT_LIST_LBL": "Lista Projetos Andamento",
            "PROJECT_TITLE_LBL": "PROJETOS ANDAMENTO",
            "PROJECT_DETAIL_LBL": "Detalhe Projeto",
            "PROJECT_DETAIL1_LBL": "Informações do Projeto",
            "PROJECT_DETAIL2_LBL": "Informações do Contrato",
            "PROJECT_DETAIL3_LBL": "Informações de localização",
            "PROJECT_DETAIL4_LBL": "Nome Projeto",
            "PROJECT_DETAIL5_LBL": "Categoria",
            "PROJECT_DETAIL6_LBL": "Fundo",
            "PROJECT_DETAIL7_LBL": "Ano",
            "PROJECT_DETAIL8_LBL": "Companhia",
            "PROJECT_DETAIL9_LBL": "Numero Contrato",
            "PROJECT_DETAIL10_LBL": "Período Inicial",
            "PROJECT_DETAIL11_LBL": "Período Final",
            "PROJECT_DETAIL12_LBL": "Orsamento",
            "PROJECT_DETAIL13_LBL": "Munisipio",
            "PROJECT_DETAIL14_LBL": "Posto Administrativo",
            "PROJECT_DETAIL15_LBL": "Suco",
            "PROJECT_DETAIL16_LBL": "Tipo Procuramento",
            "PROJECT_NEW_LIST_LBL": "Lista Novo Projeto",
            "PROJECT_NEW_TITLE_LBL": "NOVO PROJETO",
            "ANNOUNCEMENT_LIST_LBL": "Lista Anúncios",
            "ANNOUNCEMENT_TITLE_LBL": "ANÚNCIO",
            "ANNOUNCEMENT_DETAIL_LBL": "Informação Anúncio",
            "ANNOUNCEMENT_DETAIL_BREAKCUMB_LBL": "Detalhe Anúncio",
            "GET_IN_TOUCH_BREAKCUMB_LBL": "Contato",
            "APPOINTMENT_LBL": "PEDIDO ENCONTRO",
            "SUGGESTION_LBL": "SUGESTÃO",
            "CONTACT_MUNICIPALITY_LBL": "PESSOAL EDTL,EP NO MUNICÍPIO",
            "APPOINTMENT_LBL1": "Prienche as Informações Abaixo",
            "APPOINTMENT_LBL2": "Nome Completo",
            "APPOINTMENT_LBL2_1": "Prienche Nome Completo",
            "APPOINTMENT_LBL3": "Email",
            "APPOINTMENT_LBL3_1": "Prienche Email",
            "APPOINTMENT_LBL4": "Número de Telefone",
            "APPOINTMENT_LBL4_1": "Prienche Número de telefone",
            "APPOINTMENT_LBL5": "Data do Encontro",
            "APPOINTMENT_LBL6": "Hora do Encontro",
            "APPOINTMENT_LBL7": "Encontro Para",
            "APPOINTMENT_LBL8": "Sujeito",
            "APPOINTMENT_LBL8_1": "Prinche Sujeito",
            "APPOINTMENT_LBL9": "Submete",
            "APPOINTMENT_LBL10": "Dê-nos Sugestão",
            "APPOINTMENT_LBL11": "Comentário",
            "APPOINTMENT_LBL12_1": "Prienche Comentário",
            "POSITION_LBL": "Posição",
            "LIST_ALBUM_LBL": "Lista Album",
            "DETAIL_ALBUM_LBL": "Detalhe Album",
            "DETAIL_ALBUM_INFO_LBL": "Informações do Album",
            "DETAIL_ALBUM_LBL1": "Categoria",
            "DETAIL_ALBUM_LBL3": "Descrição",
            "LIST_VIDEO_LBL": "Lista Video",
            "VIDEO_LBL": "Lista Documentário",
            "FOOTER_LBL1": "Número de telefone",
            "FOOTER_LBL2": "Suporta Link",
            "FOOTER_LBL3": "Sistema Gestão Finança (Cliente)",
            "FOOTER_LBL4": "Gestão Utilizador",
            "FOOTER_LBL5": "Perguntas Frequentes",
            "FOOTER_LBL6": "Outro Sistema",
            "FOOTER_LBL7": "Join Our Newsletter",
            "FOOTER_LBL8": "Para obter nossas informações mais recentes; Por favor, insira seu e-mail abaixo",
            "FAQ_LBL": "Perguntas Frequentes",
            "FAQ_DETAIL_LBL": "Detalhe",
        }
    elif lang == "en":
        lang_data = {
            "HOME_LAST_NEWS": "LATEST NEWS",
            "BTN_READ_MORE": "Read More",
            "HOME_RECENT": "Recent Posts",
            "HOME_FAQ_TITLE": "Frequently Asked Questions",
            "HOME_VISITOR": "Visitors",
            "HOME_VISITOR_TODAY": "Today",
            "HOME_VISITOR_ALL": "Total",
            "HOME_MARQUEE": "Welcome To Electricity of Timor Leste, Public Company",
            "BREAKCUMB": "Home",
            "CATEGORY": "Categories",
            "MORE_IMAGES": "More Images",
            "SHARE_LBL": "Share to Social Media",
            "NO_IMAGE_LBL": "No Images",
            "ABOUT_LBL1": "Who We Are",
            "ABOUT_LBL2": "What We Do",
            "ABOUT_LBL3": "Board Director Profile",
            "BACKGROUND_LBL": "Background",
            "MISSION_LBL": "Mission",
            "VISION_LBL": "Vision",
            "VALUES_LBL": "Values",
            "SERVICE_LBL": "WE PROVIDE SERVICES LIKE :",
            "BOARD_MEMBER_LBL": "Member",
            "BOARD_MEMBER_DEPARTMENT_LBL": "Departament",
            "EVENT_LBL": "Event List",
            "EVENT_TITLE_LBL": "Event",
            "EVENT_START_DATE_LBL": "Start Date",
            "EVENT_END_DATE_LBL": "End Date",
            "EVENT_BREAKCUMB_LBL": "Detail Event",
            "EVENT_INFROMATION_LBL": "Information about Event",
            "RESOURCE_TITLE_LBL": "Detail Product",
            "DEPARTMENT_TITLE_LBL": "Detail Department",
            "LIST_DIVISION_TITLE_LBL": "List Division",
            "DIVISION_TITLE_LBL": "Detail Division",
            "REPORT_LIST_LBL": "List Report",
            "REPORT_TITLE__DETAIL_LBL": "Detail Report",
            "REPORT_TITLE_LBL": "REPORTS",
            "REPORT_DESCRIPTION_LBL": "Report Information",
            "VACANCY_LIST_LBL": "Vacancy List",
            "VACANCY_TITLE_LBL": "VACANCY",
            "TABEL_LBL1": "Position",
            "TABEL_LBL2": "Description",
            "TABEL_LBL3": "Start Period",
            "TABEL_LBL4": "End Period",
            "TABEL_LBL5": "Action",
            "TABEL_LBL6": "Title",
            "TABEL_LBL9": "Project Name",
            "TABEL_LBL7": "Category",
            "TABEL_LBL8": "Company",
            "ACTIVE_LBL": "Active",
            "EXPIRED_LBL": "Expired",
            "INTERNSHIP_LIST_LBL": "Internships",
            "INTERNSHIP_TITLE_LBL": "Internships",
            "VOLUNTEER_LIST_LBL": "Volunteer",
            "VOLUNTEER_TITLE_LBL": "VOLUNTEER",
            "TENDER_LIST_LBL": "Tender List",
            "TENDER_TITLE_LBL": "TENDER",
            "PROCURAMENT_LIST_LBL": "Procurement Guideline",
            "PROCURAMENT_TITLE_LBL": "PROCUREMENT GUIDELINE",
            "POLICY_LIST_LBL": "Policy and Rules List",
            "POLICY_TITLE_LBL": "POLICY AND RULES",
            "PROJECT_LIST_LBL": "Project Ongoing List",
            "PROJECT_TITLE_LBL": "ONGOING PROJECT",
            "PROJECT_DETAIL_LBL": "Detail Project",
            "PROJECT_DETAIL1_LBL": "Project Information",
            "PROJECT_DETAIL2_LBL": "Contract Information",
            "PROJECT_DETAIL3_LBL": "Location Information",
            "PROJECT_DETAIL4_LBL": "Project Name",
            "PROJECT_DETAIL5_LBL": "Category",
            "PROJECT_DETAIL6_LBL": "Fund",
            "PROJECT_DETAIL7_LBL": "Year",
            "PROJECT_DETAIL8_LBL": "Company",
            "PROJECT_DETAIL16_LBL": "Type of Procurament",
            "PROJECT_DETAIL9_LBL": "Contract Number",
            "PROJECT_DETAIL10_LBL": "Start Period",
            "PROJECT_DETAIL11_LBL": "End Period",
            "PROJECT_DETAIL12_LBL": "Budget",
            "PROJECT_DETAIL13_LBL": "Municipality",
            "PROJECT_DETAIL14_LBL": "Administrative Post",
            "PROJECT_DETAIL15_LBL": "Village",
            "PROJECT_NEW_LIST_LBL": "Up Coming Project List",
            "PROJECT_NEW_TITLE_LBL": "UP COMING PROJECT",
            "ANNOUNCEMENT_LIST_LBL": "Announcement List",
            "ANNOUNCEMENT_TITLE_LBL": "ANNOUNCEMENT",
            "ANNOUNCEMENT_DETAIL_LBL": "Announcement Information",
            "ANNOUNCEMENT_DETAIL_BREAKCUMB_LBL": "Announcement Detail",
            "GET_IN_TOUCH_BREAKCUMB_LBL": "Get In Touch",
            "APPOINTMENT_LBL": "MAKE APPOINTMENT",
            "SUGGESTION_LBL": "SUGGESTION",
            "CONTACT_MUNICIPALITY_LBL": "STAFF EDTL,EP ON MUNICIPALITY",
            "APPOINTMENT_LBL1": "Fill Information Below",
            "APPOINTMENT_LBL2": "Full Name",
            "APPOINTMENT_LBL2_1": "Enter your Full Name",
            "APPOINTMENT_LBL3": "Email",
            "APPOINTMENT_LBL3_1": "Enter your Email",
            "APPOINTMENT_LBL4": "Phone Number",
            "APPOINTMENT_LBL4_1": "Enter Phone Number",
            "APPOINTMENT_LBL5": "Appointment Date",
            "APPOINTMENT_LBL6": "Appointment Time",
            "APPOINTMENT_LBL7": "Appointment To",
            "APPOINTMENT_LBL8": "Subject",
            "APPOINTMENT_LBL8_1": "Enter Subject",
            "APPOINTMENT_LBL9": "Submit",
            "APPOINTMENT_LBL10": "Give Us Suggestion",
            "APPOINTMENT_LBL11": "Comment",
            "APPOINTMENT_LBL12_1": "Enter Comment",
            "POSITION_LBL": "Position",
            "LIST_ALBUM_LBL": "Album List",
            "DETAIL_ALBUM_LBL": "Album Detail",
            "DETAIL_ALBUM_INFO_LBL": "Album Information",
            "DETAIL_ALBUM_LBL1": "Category",
            "DETAIL_ALBUM_LBL2": "Description",
            "LIST_VIDEO_LBL": "Video List",
            "VIDEO_LBL": "Documentary List",
            "FOOTER_LBL1": "Phone Number",
            "FOOTER_LBL2": "Useful Links",
            "FOOTER_LBL3": "Finance Management System (Client)",
            "FOOTER_LBL4": "User Subscribe Management",
            "FOOTER_LBL5": "Frequently Asked Questions",
            "FOOTER_LBL6": "Our Systems",
            "FOOTER_LBL7": "Join Our Newsletter",
            "FOOTER_LBL8": "To Get our latest information; Please Enter your email on the field bellow",
            "FAQ_LBL": "Frequently Asked Questions",
            "FAQ_DETAIL_LBL": "Detail FAQ",
        }   
    # lang_data.append([LANG_NEWS])
    return lang_data