# Generated by Django 3.2.9 on 2022-01-24 23:46

from django.db import migrations, models
import profiles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_tet', models.TextField(blank=True, null=True)),
                ('mission_tet', models.TextField(blank=True, null=True)),
                ('motto_tet', models.TextField(blank=True, null=True)),
                ('vision_por', models.TextField(blank=True, null=True)),
                ('mission_por', models.TextField(blank=True, null=True)),
                ('motto_por', models.TextField(blank=True, null=True)),
                ('vision_eng', models.TextField(blank=True, null=True)),
                ('mission_eng', models.TextField(blank=True, null=True)),
                ('motto_eng', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=profiles.utils.path_and_rename_about)),
                ('org_chart', models.FileField(blank=True, null=True, upload_to=profiles.utils.path_and_rename_orgchart)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
