# Generated by Django 3.2.9 on 2022-01-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220125_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name_tet', models.CharField(blank=True, max_length=50, null=True)),
                ('name_por', models.CharField(blank=True, max_length=50, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=50, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('image', models.ImageField(default='person.jpg', null=True, upload_to='employee_image/')),
                ('hashed', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('division', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.division')),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='profiles.employee')),
            ],
        ),
    ]
