# Generated by Django 3.2.9 on 2022-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_division_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='end_period',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
