# Generated by Django 3.2.9 on 2022-01-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220126_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='wwwa_eng',
            new_name='wwa_eng',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwwa_por',
            new_name='wwa_por',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwwa_tet',
            new_name='wwa_tet',
        ),
    ]
