# Generated by Django 3.2.9 on 2022-01-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220126_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
