# Generated by Django 3.2.9 on 2022-01-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220127_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
