# Generated by Django 3.2.9 on 2022-02-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_division_position_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.TextField(null=True),
        ),
    ]
