# Generated by Django 3.2.9 on 2022-02-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20220212_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
