# Generated by Django 3.2.9 on 2022-02-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20220212_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='end_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
