# Generated by Django 3.2.9 on 2022-02-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20220212_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='end_period',
        ),
        migrations.RemoveField(
            model_name='position',
            name='start_period',
        ),
    ]
