# Generated by Django 3.2.9 on 2022-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20220212_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='group',
            field=models.CharField(choices=[('Board Member', 'Board Member'), ('Department', 'Division'), ('Division', 'Division')], max_length=200, null=True),
        ),
    ]
