# Generated by Django 3.2.9 on 2022-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_position_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='group',
            field=models.CharField(choices=[('Board Member', 'Board Member'), ('Department', 'Department'), ('Division', 'Division')], max_length=200, null=True),
        ),
    ]
