# Generated by Django 3.2.9 on 2022-02-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_position_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='intro_eng',
            new_name='background_eng',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='intro_por',
            new_name='background_por',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='intro_tet',
            new_name='background_tet',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='motto_eng',
            new_name='mission_eng',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='motto_por',
            new_name='mission_por',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='motto_tet',
            new_name='mission_tet',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwa_eng',
            new_name='objective_eng',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwa_por',
            new_name='objective_por',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwa_tet',
            new_name='objective_tet',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwd_eng',
            new_name='vision_eng',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwd_por',
            new_name='vision_por',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='wwd_tet',
            new_name='vision_tet',
        ),
        migrations.RemoveField(
            model_name='about',
            name='org_chart',
        ),
    ]
