# Generated by Django 3.2.9 on 2022-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20220215_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='values_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='values_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='values_tet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
