# Generated by Django 3.2.9 on 2022-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
