# Generated by Django 3.2.9 on 2022-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_service_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_tet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
