# Generated by Django 3.2.9 on 2022-02-24 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0026_alter_position_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverasaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tet', models.CharField(max_length=254)),
                ('title_por', models.CharField(max_length=254, null=True)),
                ('title_eng', models.CharField(max_length=254, null=True)),
                ('description_tet', models.TextField(blank=True, null=True)),
                ('description_por', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=profiles.utils.path_and_rename_deliverasaun, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('date', models.DateField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
