# Generated by Django 3.2.9 on 2022-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
