# Generated by Django 3.2.9 on 2022-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_client_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='addresss',
            new_name='address',
        ),
    ]
