# Generated by Django 3.2.9 on 2022-02-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_addresss_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='temp_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
