# Generated by Django 3.2.9 on 2022-02-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_client_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_kontador',
            field=models.PositiveBigIntegerField(),
        ),
    ]
