# Generated by Django 3.2.9 on 2022-02-05 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_alter_client_numero_kontador'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
