# Generated by Django 3.2.9 on 2022-02-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20220205_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
