# Generated by Django 3.2.9 on 2022-02-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_bill_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
