# Generated by Django 3.2.9 on 2022-02-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bill_done_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
